/* Axtor POS Cloud demo fixes: product media/category/SKU, suppliers, industry fields, credit days, SOA, reports. */
(function(){
  const KEY='axtorAdvancedDemoDB';
  const $=(s,r=document)=>r.querySelector(s); const $$=(s,r=document)=>Array.from(r.querySelectorAll(s));
  const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const num=v=>Number(v||0)||0;
  const money=v=>'QAR '+num(v).toLocaleString(undefined,{minimumFractionDigits:num(v)%1?2:0,maximumFractionDigits:2});
  function db(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(e){return {}}}
  function save(d){localStorage.setItem(KEY,JSON.stringify(d||{}));}
  function toast(msg,type='success'){ if(window.AxtorToast) return window.AxtorToast(msg,type); const el=document.createElement('div'); el.className=`position-fixed bottom-0 end-0 m-3 alert alert-${type} shadow`; el.style.zIndex=10000; el.textContent=msg; document.body.appendChild(el); setTimeout(()=>el.remove(),2400); }
  function activeProducts(){return (db().products||[]).filter(p=>p && p.deleted!==true)}
  function productName(p){return String(p?.name||p?.product||'Item')}
  function selectedIndustry(){const d=db(); return d.selectedIndustry||localStorage.getItem('axtorSelectedIndustry')||'Paint Store'}
  const industryFields={
    'Paint Store':[['colorCode','Color Code'],['brand','Brand'],['formulaShade','Formula / Shade'],['thinnerRatio','Thinner Ratio']],
    Pharmacy:[['batchNo','Batch No'],['expiryDate','Expiry Date','date'],['prescriptionRequired','Prescription Required','select','No|Yes']],
    Grocery:[['expiryDate','Expiry Date','date'],['weighingScale','Weighing Scale','select','No|Yes'],['freshStock','Fresh Stock','select','No|Yes']],
    'Auto Parts':[['partNumber','Part Number'],['oemReference','OEM Reference'],['vehicleModel','Vehicle Model']],
    Restaurant:[['kitchenItem','Kitchen Item','select','No|Yes'],['serviceOption','Table / Service Option'],['prepNote','Preparation Note']],
    Electronics:[['serialImei','Serial / IMEI'],['warrantyPeriod','Warranty Period']],
    Wholesale:[['priceLevel','Price Level'],['customerGroup','Customer Group'],['taxMode','Tax Mode']],
    Retail:[['priceLevel','Price Level'],['customerGroup','Customer Group'],['taxMode','Tax Mode']]
  };
  function migrate(){ const d=db(); let changed=false; d.products=d.products||[]; d.customers=d.customers||[]; d.invoices=d.invoices||[]; d.productCategories=d.productCategories||[]; d.suppliers=d.suppliers||[];
    const catSet=new Set(d.productCategories.map(c=>String(c).toLowerCase())); d.products.forEach(p=>{ if(p.category && !catSet.has(String(p.category).toLowerCase())){d.productCategories.push(p.category); catSet.add(String(p.category).toLowerCase()); changed=true;} if(p.deleted===undefined){p.deleted=false; changed=true;} });
    ['Automotive Paint','Industrial Coating','Wood Coating','Thinner','Clear Coat','Automotive','Industrial'].forEach(c=>{ if(!catSet.has(c.toLowerCase())){d.productCategories.push(c); catSet.add(c.toLowerCase()); changed=true;} });
    const supplierNames=new Set(d.suppliers.map(s=>String(s.name).toLowerCase())); (d.supplierBills||[]).forEach(b=>{ if(b.supplier && !supplierNames.has(String(b.supplier).toLowerCase())){d.suppliers.push({id:'SUP-'+String(d.suppliers.length+1).padStart(3,'0'),name:b.supplier,phone:b.supplier==='Starlux Paints'?'4411 9922':'4488 3377',email:'',company:b.supplier,address:'',openingBalance:0,creditDays:30,active:true}); supplierNames.add(String(b.supplier).toLowerCase()); changed=true;} });
    d.customers.forEach(c=>{ if(!c.creditDays){c.creditDays=30; changed=true;} });
    if(!d.selectedIndustry){d.selectedIndustry=localStorage.getItem('axtorSelectedIndustry')||'Paint Store'; changed=true;}
    if(changed) save(d); return d; }
  function fillCategorySelect(){ const sel=$('#productCategoryInput'); if(!sel) return; const current=sel.value; sel.innerHTML=(migrate().productCategories||[]).map(c=>`<option>${esc(c)}</option>`).join(''); if(current) sel.value=current; }
  function customFieldsHtml(){ const f=industryFields[selectedIndustry()]||industryFields.Retail; return `<div class="col-12"><div class="alert alert-success py-2 mb-0"><b>Industry:</b> ${esc(selectedIndustry())} fields are active from Setup Wizard.</div></div>`+f.map(a=>{ const [key,label,type,opt]=a; if(type==='select') return `<div class="col-md-3 industry-field"><label class="form-label">${esc(label)}</label><select class="form-select" data-product-custom="${esc(key)}">${opt.split('|').map(o=>`<option>${esc(o)}</option>`).join('')}</select></div>`; return `<div class="col-md-3 industry-field"><label class="form-label">${esc(label)}</label><input class="form-control" type="${type||'text'}" data-product-custom="${esc(key)}"></div>`; }).join(''); }
  function enhanceProductForm(){ if(!$('#add-product')||$('#productImageInput')) return; fillCategorySelect(); const sku=$('#productSkuInput'), bar=$('#productBarcodeInput'), cat=$('#productCategoryInput'), row=$('#saveProductBtn')?.closest('.row');
    sku?.insertAdjacentHTML('afterend','<button type="button" class="btn btn-soft btn-sm mt-2" id="autoSkuBtn"><i class="bi bi-magic"></i> Auto SKU</button>');
    bar?.insertAdjacentHTML('afterend','<button type="button" class="btn btn-soft btn-sm mt-2" id="genBarcodeBtn"><i class="bi bi-upc"></i> Generate Barcode</button>');
    cat?.insertAdjacentHTML('afterend','<button type="button" class="btn btn-soft btn-sm mt-2" id="addCategoryBtn"><i class="bi bi-plus-lg"></i> Add New Category</button>');
    $('#productOpeningStockInput')?.closest('.col-md-4')?.insertAdjacentHTML('afterend','<div class="col-md-4"><label class="form-label">Product Picture</label><input id="productImageInput" class="form-control" type="file" accept="image/*"><small class="text-muted">Saved as base64 Data URL in localStorage demo.</small></div><div class="col-md-2"><label class="form-label">Preview</label><div id="productImagePreview" class="border rounded d-flex align-items-center justify-content-center" style="height:64px"><i class="bi bi-image text-muted"></i></div></div>');
    $('#saveProductBtn')?.closest('.col-12')?.insertAdjacentHTML('beforebegin',`<div class="row g-3" id="industryProductFields">${customFieldsHtml()}</div>`);
    $('#autoSkuBtn')?.addEventListener('click',()=>{ const max=activeProducts().reduce((m,p)=>{const n=Number(String(p.sku||'').match(/AX-(\d+)/)?.[1]||0); return Math.max(m,n);},0); $('#productSkuInput').value='AX-'+String(max+1).padStart(4,'0'); });
    $('#genBarcodeBtn')?.addEventListener('click',()=>{$('#productBarcodeInput').value=String(Date.now()).slice(-12);});
    $('#productBarcodeInput')?.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault(); toast('Barcode confirmed: '+e.target.value)}});
    $('#addCategoryBtn')?.addEventListener('click',()=>{ const name=prompt('New category name'); if(!name) return; const d=db(); d.productCategories=d.productCategories||[]; if(d.productCategories.some(c=>String(c).toLowerCase()===name.trim().toLowerCase())) return toast('Category already exists','warning'); d.productCategories.push(name.trim()); save(d); fillCategorySelect(); $('#productCategoryInput').value=name.trim(); toast('Category added'); });
    $('#productImageInput')?.addEventListener('change',e=>{ const file=e.target.files?.[0]; if(!file) return; const r=new FileReader(); r.onload=()=>{$('#productImagePreview').innerHTML=`<img src="${r.result}" style="max-height:60px;max-width:100%;object-fit:cover;border-radius:8px">`; $('#productImagePreview').dataset.imageData=r.result;}; r.readAsDataURL(file); });
    $('#saveProductBtn')?.addEventListener('click',e=>{ e.preventDefault(); e.stopImmediatePropagation(); const name=$('#productNameInput')?.value.trim(); if(!name) return toast('Product name required','warning'); const d=migrate(); const sku=$('#productSkuInput')?.value.trim() || ('AX-'+String(activeProducts().length+1).padStart(4,'0')); const barcode=$('#productBarcodeInput')?.value.trim(); const custom={}; $$('[data-product-custom]').forEach(i=>custom[i.dataset.productCustom]=i.value); const row={sku,barcode,name,category:$('#productCategoryInput')?.value||'General',price:num($('#productSalePriceInput')?.value),stock:num($('#productOpeningStockInput')?.value),status:num($('#productOpeningStockInput')?.value)>0?'In stock':'Low',imageData:$('#productImagePreview')?.dataset.imageData||'',customFields:custom,industry:selectedIndustry(),deleted:false}; const idx=d.products.findIndex(p=>String(p.sku).toLowerCase()===sku.toLowerCase() || (barcode && String(p.barcode).toLowerCase()===barcode.toLowerCase())); if(idx>=0) d.products[idx]={...d.products[idx],...row}; else d.products.push(row); if(!d.productCategories.some(c=>String(c).toLowerCase()===row.category.toLowerCase())) d.productCategories.push(row.category); save(d); renderProducts(); renderSaleGrid(); renderTerminalGrid(); toast('Product saved with image/category/SKU/barcode'); },true);
  }
  function renderProducts(){ const body=$('#productsTableBody'); if(!body) return; const table=body.closest('table'); const h=table?.querySelector('thead tr'); if(h) h.innerHTML='<th>Image</th><th>SKU</th><th>Name</th><th>Category</th><th>Barcode</th><th>Price</th><th>Stock</th><th>Status</th><th>Actions</th>'; const rows=activeProducts().map(p=>{ const img=p.imageData||p.image; const custom=p.customFields?`<br><small class="text-muted">${Object.entries(p.customFields).filter(x=>x[1]).slice(0,2).map(([k,v])=>esc(k)+': '+esc(v)).join(' • ')}</small>`:''; return `<tr><td>${img?`<img src="${img}" style="width:42px;height:42px;object-fit:cover;border-radius:8px">`:'<span class="quick-icon" style="width:42px;height:42px"><i class="bi bi-box-seam"></i></span>'}</td><td>${esc(p.sku)}</td><td>${esc(productName(p))}${custom}</td><td>${esc(p.category)}</td><td>${esc(p.barcode||'-')}</td><td>${money(p.price)}</td><td>${num(p.stock)}</td><td><span class="badge-soft ${num(p.stock)>5?'badge-paid':'badge-danger-soft'}">${num(p.stock)>5?'In stock':'Low'}</span></td><td><button class="btn btn-sm btn-soft" data-edit-product="${esc(p.sku)}">Edit</button> <button class="btn btn-sm btn-soft text-danger" data-delete-product="${esc(p.sku)}">Delete</button></td></tr>`; }).join(''); body.innerHTML=rows||'<tr><td colspan="9" class="text-muted">No active products.</td></tr>'; }
  function renderSaleGrid(){ const grid=$('#newSaleProductGrid'); if(!grid) return; const q=($('#newSaleProductSearch')?.value||'').toLowerCase(); const list=activeProducts().filter(p=>!q||`${p.sku||''} ${p.barcode||''} ${p.name||''} ${p.category||''}`.toLowerCase().includes(q)); grid.innerHTML=list.map(p=>`<div class="col-md-4"><div class="pos-product"><div class="pos-img">${p.imageData||p.image?`<img src="${p.imageData||p.image}" style="width:100%;height:100%;object-fit:cover;border-radius:12px">`:'<i class="bi bi-box-seam"></i>'}</div><strong>${esc(productName(p))}</strong><small class="text-muted">SKU ${esc(p.sku||'-')}${p.barcode?' • '+esc(p.barcode):''}</small><div class="d-flex justify-content-between"><span class="fw-bold">${money(p.price)}</span><button class="btn btn-sm btn-brand" data-add-cart data-sku="${esc(p.sku||'')}" data-barcode="${esc(p.barcode||'')}" data-name="${esc(productName(p))}" data-price="${num(p.price)}">Add</button></div></div></div>`).join('')||'<div class="col-12"><div class="text-muted text-center py-4">No product found.</div></div>'; }
  function renderTerminalGrid(){ const grid=$('#terminalProductGrid'); if(!grid) return; const q=($('#terminalProductSearch')?.value||'').toLowerCase(); const list=activeProducts().filter(p=>!q||`${p.sku||''} ${p.barcode||''} ${p.name||''} ${p.category||''}`.toLowerCase().includes(q)); grid.innerHTML=list.map(p=>`<div class="fast-product"><div class="product-icon">${p.imageData||p.image?`<img src="${p.imageData||p.image}" style="width:100%;height:100%;object-fit:cover;border-radius:12px">`:'<i class="bi bi-box-seam"></i>'}</div><strong>${esc(productName(p))}</strong><small class="text-muted">${esc(p.sku)} • Stock ${num(p.stock)}</small><div class="d-flex justify-content-between align-items-center mt-auto"><span class="fw-bold">${money(p.price)}</span><button class="btn btn-sm btn-brand" data-terminal-add="${esc(p.sku)}">Add</button></div></div>`).join(''); }
  function initProductActions(){ document.addEventListener('click',e=>{ const del=e.target.closest('[data-delete-product]'); if(del){ e.preventDefault(); e.stopImmediatePropagation(); if(!confirm('Delete this product from active lists? Old invoices will stay safe.')) return; const d=db(); const p=(d.products||[]).find(x=>String(x.sku)===String(del.dataset.deleteProduct)); if(p) p.deleted=true; save(d); renderProducts(); renderSaleGrid(); renderTerminalGrid(); toast('Product deleted from active list'); } const edit=e.target.closest('[data-edit-product]'); if(edit){ const p=activeProducts().find(x=>String(x.sku)===String(edit.dataset.editProduct)); if(!p) return; location.hash='#add-product'; window.AxtorActivateHash&&window.AxtorActivateHash(); setTimeout(()=>{enhanceProductForm(); $('#productNameInput').value=productName(p); $('#productSkuInput').value=p.sku||''; $('#productBarcodeInput').value=p.barcode||''; fillCategorySelect(); $('#productCategoryInput').value=p.category||''; $('#productSalePriceInput').value=p.price||0; $('#productOpeningStockInput').value=p.stock||0; if(p.imageData||p.image){$('#productImagePreview').dataset.imageData=p.imageData||p.image; $('#productImagePreview').innerHTML=`<img src="${p.imageData||p.image}" style="max-height:60px;max-width:100%;object-fit:cover;border-radius:8px">`;} },50); } },true); $('#newSaleProductSearch')?.addEventListener('input',()=>setTimeout(renderSaleGrid,0)); $('#terminalProductSearch')?.addEventListener('input',()=>setTimeout(renderTerminalGrid,0)); }
  function initSuppliers(){ if(!$('#supplier-list')||$('#add-supplier')) return; const tabs=$('.nav-tabs'); tabs?.insertAdjacentHTML('beforeend','<li class="nav-item"><button class="nav-link" data-bs-toggle="tab" data-bs-target="#add-supplier">Add Supplier</button></li>'); $('.tab-content')?.insertAdjacentHTML('beforeend',`<section class="tab-pane fade section-anchor" id="add-supplier"><div class="cardx"><h5 class="cardx-title mb-3">Add Supplier</h5><div class="row g-3"><div class="col-md-4"><label class="form-label">Supplier name</label><input id="supplierNameInput" class="form-control"></div><div class="col-md-4"><label class="form-label">Phone</label><input id="supplierPhoneInput" class="form-control"></div><div class="col-md-4"><label class="form-label">Email</label><input id="supplierEmailInput" class="form-control"></div><div class="col-md-4"><label class="form-label">Company / Brand</label><input id="supplierCompanyInput" class="form-control"></div><div class="col-md-4"><label class="form-label">Opening balance</label><input id="supplierOpeningInput" class="form-control" type="number" value="0"></div><div class="col-md-4"><label class="form-label">Credit days</label><input id="supplierCreditDaysInput" class="form-control" type="number" value="30"></div><div class="col-md-4"><label class="form-label">Status</label><select id="supplierStatusInput" class="form-select"><option value="true">Active</option><option value="false">Inactive</option></select></div><div class="col-12"><label class="form-label">Address</label><textarea id="supplierAddressInput" class="form-control" rows="2"></textarea></div><div class="col-12"><button id="saveSupplierBtn" class="btn btn-brand">Save Supplier</button></div></div></div></section>`); renderSuppliers(); $('#saveSupplierBtn')?.addEventListener('click',()=>{ const name=$('#supplierNameInput').value.trim(); if(!name) return toast('Supplier name required','warning'); const d=migrate(); const row={id:'SUP-'+String((d.suppliers||[]).length+1).padStart(3,'0'),name,phone:$('#supplierPhoneInput').value.trim(),email:$('#supplierEmailInput').value.trim(),company:$('#supplierCompanyInput').value.trim(),address:$('#supplierAddressInput').value.trim(),openingBalance:num($('#supplierOpeningInput').value),creditDays:num($('#supplierCreditDaysInput').value)||30,active:$('#supplierStatusInput').value==='true'}; const i=d.suppliers.findIndex(s=>String(s.name).toLowerCase()===name.toLowerCase()||String(s.id)===row.id); if(i>=0)d.suppliers[i]={...d.suppliers[i],...row,id:d.suppliers[i].id}; else d.suppliers.push(row); if(row.openingBalance>0 && !(d.supplierBills||[]).some(b=>b.no==='OPEN-'+row.name)){d.supplierBills=d.supplierBills||[]; d.supplierBills.push({no:'OPEN-'+row.name,supplier:row.name,date:new Date().toLocaleDateString('en-GB'),due:row.creditDays+' days',total:row.openingBalance,paid:0});} save(d); renderSuppliers(); toast('Supplier saved'); }); }
  function renderSuppliers(){ if(!$('#supplierListBody')) return; const d=migrate(); $('#supplierListBody').innerHTML=(d.suppliers||[]).map(s=>{const bal=(d.supplierBills||[]).filter(b=>b.supplier===s.name).reduce((a,b)=>a+Math.max(0,num(b.total)-num(b.paid)),num(s.openingBalance)); return `<tr><td>${esc(s.name)}</td><td>${esc(s.phone||'-')}</td><td>${money(bal)}</td><td><span class="badge-soft ${s.active!==false?'badge-paid':'badge-danger-soft'}">${s.active!==false?'Active':'Inactive'}</span></td></tr>`;}).join(''); const opts=(d.suppliers||[]).filter(s=>s.active!==false).map(s=>`<option>${esc(s.name)}</option>`).join(''); ['supplierPaymentSupplier'].forEach(id=>{const el=$('#'+id); if(el) el.innerHTML=opts;}); const soa=$('#supplier-soa select'); if(soa) soa.innerHTML=opts; }
  function initCreditDays(){ const add=$('#add-customer .row'); if(add && !$('#customerCreditDaysInput')) $('#saveCustomerBtn')?.closest('.col-12')?.insertAdjacentHTML('beforebegin','<div class="col-md-6"><label class="form-label">Credit days</label><select id="customerCreditDaysInput" class="form-select"><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option><option value="120">120 days</option></select></div>'); const cartCard=$('#newSaleSalesmanId')?.closest('.cardx'); if(cartCard && !$('#newSaleCreditDays')) $('#newSaleSalesmanId').closest('.row')?.insertAdjacentHTML('afterend','<div class="row g-2 mb-3"><div class="col-md-12"><label class="form-label fw-semibold"><i class="bi bi-calendar2-check me-1"></i>Credit Days</label><select id="newSaleCreditDays" class="form-select"><option value="customer">Customer default</option><option value="30">30 days</option><option value="60">60 days</option><option value="90">90 days</option><option value="120">120 days</option></select></div></div>'); $('#newSaleCustomer')?.addEventListener('change',()=>{ const c=(db().customers||[]).find(x=>x.name===$('#newSaleCustomer').value); if($('#newSaleCreditDays')) $('#newSaleCreditDays').value=String(c?.creditDays||30); }); $('#completeSaleBtn')?.addEventListener('click',()=>setTimeout(()=>{ const d=db(); const inv=d.invoices?.[0]; if(!inv) return; const cust=(d.customers||[]).find(c=>c.name===inv.customer); const days=$('#newSaleCreditDays')?.value==='customer'?num(cust?.creditDays||30):num($('#newSaleCreditDays')?.value||cust?.creditDays||30); inv.creditDays=days; const due=new Date(); due.setDate(due.getDate()+days); inv.dueDate=due.toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'}); const rec=(d.customerCreditInvoices||[]).find(x=>x.no===inv.no); if(rec){rec.due=inv.dueDate; rec.creditDays=days;} save(d); },50)); }
  function initCustomerSOA(){ const sec=$('#customer-soa'); if(!sec) return; const sel=sec.querySelector('select'); const btn=sec.querySelector('button'); const body=sec.querySelector('tbody'); function fill(){ const current=sel.value; sel.innerHTML=(migrate().customers||[]).map(c=>`<option>${esc(c.name)}</option>`).join(''); if(current) sel.value=current; } function run(){ const d=db(); const name=sel.value; const c=(d.customers||[]).find(x=>x.name===name)||{}; let bal=0; const rows=[]; if(num(c.openingBalance||c.balance)){bal+=num(c.openingBalance||0); rows.push({date:'Opening',ref:'OPEN',desc:'Opening Balance',debit:num(c.openingBalance||0),credit:0,bal});} (d.invoices||[]).filter(i=>i.customer===name&&!String(i.status).toLowerCase().includes('draft')).forEach(i=>{bal+=num(i.total||i.amount); rows.push({date:i.date||'',ref:i.no||'',desc:'Sales Invoice'+(i.dueDate?' due '+i.dueDate:''),debit:num(i.total||i.amount),credit:0,bal}); if(num(i.paid)>0){bal-=num(i.paid); rows.push({date:i.date||'',ref:(i.no||'')+' PAID',desc:'Invoice Payment',debit:0,credit:num(i.paid),bal});}}); (d.customerPayments||[]).filter(p=>p.customer===name).forEach(p=>{bal-=num(p.amount); rows.push({date:p.date||'',ref:p.no||'',desc:'Customer Receipt',debit:0,credit:num(p.amount),bal});}); body.innerHTML=rows.map(r=>`<tr><td>${esc(r.date)}</td><td>${esc(r.ref)}</td><td>${esc(r.desc)}</td><td>${r.debit?money(r.debit):'-'}</td><td>${r.credit?money(r.credit):'-'}</td><td>${money(r.bal)}</td></tr>`).join('')||'<tr><td colspan="6" class="text-muted">No SOA entries for this customer yet.</td></tr>'; } fill(); run(); btn?.addEventListener('click',e=>{e.preventDefault(); run();}); }
  function initSetup(){ if(!$('#industryCards')) return; const show=()=>{ const d=migrate(); localStorage.setItem('axtorSelectedIndustry',d.selectedIndustry); $$('#selectedIndustryText,[data-selected-industry]').forEach(x=>x.textContent=d.selectedIndustry); }; document.addEventListener('click',e=>{ const card=e.target.closest('[data-industry]'); if(card) setTimeout(show,0); }); show(); }
  function initReports(){ if(!$('.quick-card')) return; const preview=document.createElement('section'); preview.className='section-anchor mt-4'; preview.id='report-preview'; preview.innerHTML='<div class="cardx"><div class="d-flex justify-content-between align-items-center mb-3"><div><h5 class="cardx-title" id="activeReportTitle">Report Preview</h5><p class="text-muted mb-0" id="activeReportMeta">LocalStorage demo data</p></div><button class="btn btn-soft" id="printActiveReport"><i class="bi bi-printer"></i> Print / Export PDF</button></div><div id="activeReportSummary" class="row g-3 mb-3"></div><div class="table-wrap"><table class="table"><thead id="activeReportHead"></thead><tbody id="activeReportBody"></tbody></table></div></div>'; $('.page')?.appendChild(preview); function report(title){ const d=db(), inv=d.invoices||[], prod=d.products||[], pays=d.customerPayments||[]; let heads=['Date','Ref','Description','Debit','Credit'], rows=[]; if(title.includes('Product')){heads=['SKU','Product','Qty Sold','Sales']; const map={}; inv.forEach(i=>(i.items||[]).forEach(x=>{const k=x.sku||x.name; map[k]=map[k]||{sku:x.sku,name:x.name||x.product,qty:0,sales:0}; map[k].qty+=num(x.qty); map[k].sales+=num(x.qty)*num(x.price||x.rate);})); rows=Object.values(map).map(x=>[x.sku,x.name,x.qty,money(x.sales)]);} else if(title.includes('Customer')){heads=['Customer','Invoices','Sales','Paid','Balance']; const names=[...new Set(inv.map(i=>i.customer))]; rows=names.map(n=>{const a=inv.filter(i=>i.customer===n); const sales=a.reduce((s,i)=>s+num(i.total||i.amount),0); const paid=a.reduce((s,i)=>s+num(i.paid),0); return [n,a.length,money(sales),money(paid),money(sales-paid)];});} else if(title.includes('Stock')){heads=['SKU','Product','Category','Stock','Value']; rows=prod.filter(p=>!p.deleted).map(p=>[p.sku,p.name,p.category,num(p.stock),money(num(p.stock)*num(p.price))]);} else if(title.includes('Tax')){heads=['Invoice','Customer','Subtotal','Tax','Total']; rows=inv.map(i=>[i.no,i.customer,money(i.subtotal),money(i.tax),money(i.total||i.amount)]);} else if(title.includes('Purchase')){heads=['Bill','Supplier','Due','Total','Paid']; rows=(d.supplierBills||[]).map(b=>[b.no,b.supplier,b.due,money(b.total),money(b.paid)]);} else if(title.includes('Commission')){heads=['Salesman','Month','Target','Actual','Commission']; rows=(d.salesmanTargets||[]).map(t=>{const sm=(d.salesmen||[]).find(s=>s.id===t.salesmanId); const actual=inv.filter(i=>i.salesmanId===t.salesmanId).reduce((s,i)=>s+num(i.total||i.amount),0); return [sm?.name||t.salesmanId,t.month,money(t.targetAmount),money(actual),money(actual*.02)];});} else {heads=['Date','Ref','Customer','Total','Paid','Balance']; rows=inv.filter(i=>!String(i.status).toLowerCase().includes('draft')).map(i=>[i.date,i.no,i.customer,money(i.total||i.amount),money(i.paid),money(num(i.balance))]);}
      $('#activeReportTitle').textContent=title; $('#activeReportMeta').textContent='Date filter: current demo range • Branch: all branches'; $('#activeReportHead').innerHTML='<tr>'+heads.map(h=>`<th>${h}</th>`).join('')+'</tr>'; $('#activeReportBody').innerHTML=rows.map(r=>'<tr>'+r.map(c=>`<td>${esc(c)}</td>`).join('')+'</tr>').join('')||`<tr><td colspan="${heads.length}" class="text-muted">No data for this report.</td></tr>`; $('#activeReportSummary').innerHTML=`<div class="col-md-4"><div class="mini-stat"><span>Rows</span><h5>${rows.length}</h5></div></div><div class="col-md-4"><div class="mini-stat"><span>Total Sales</span><h5>${money(inv.reduce((s,i)=>s+num(i.total||i.amount),0))}</h5></div></div><div class="col-md-4"><div class="mini-stat"><span>Products</span><h5>${prod.filter(p=>!p.deleted).length}</h5></div></div>`; location.hash='report-preview'; }
    $$('.quick-card').forEach(a=>{const title=a.querySelector('strong')?.textContent||'Report'; a.href='#report-preview'; a.dataset.reportTitle=title;}); document.addEventListener('click',e=>{ const card=e.target.closest('.quick-card'); if(card){e.preventDefault(); report(card.dataset.reportTitle||'Report');} if(e.target.closest('#printActiveReport')) window.print(); if(e.target.closest('[data-demo-action="Reports refreshed"]')) report($('#activeReportTitle')?.textContent||'Daily Sale Report'); }); report('Daily Sale Report'); }
  function initPaymentZero(){ const modal=$('#paymentModal'); if(!modal) return; modal.addEventListener('show.bs.modal',()=>setTimeout(()=>{ const amt=$('#paymentModalAmount'); if(amt){amt.value='0.00'; const total=num(($('[data-payment-total]')?.textContent||'0').replace(/[^0-9.]/g,'')); const bal=$('#paymentModalBalance'); if(bal) bal.textContent=money(total);} if(!$('#fullPaidBtn')) $('#paymentModalAmount')?.insertAdjacentHTML('afterend','<button type="button" class="btn btn-soft btn-sm mt-2" id="fullPaidBtn">Full Paid</button>'); },0)); document.addEventListener('click',e=>{ if(e.target.closest('#fullPaidBtn')){ const txt=$('[data-payment-total]')?.textContent||'0'; $('#paymentModalAmount').value=String(num(txt.replace(/[^0-9.]/g,''))).replace(/^$/,'0'); $('#paymentModalAmount').dispatchEvent(new Event('input',{bubbles:true})); }}); }
  document.addEventListener('DOMContentLoaded',()=>{ migrate(); enhanceProductForm(); initProductActions(); renderProducts(); setTimeout(()=>{renderSaleGrid(); renderTerminalGrid();},80); initSuppliers(); initCreditDays(); initCustomerSOA(); initSetup(); initReports(); initPaymentZero(); });
})();
